# https://travis-ci.org/jwtk/jjwt

dist: trusty
sudo: required

language: java

matrix:
  include:
    - jdk: oraclejdk8
      addons:
      apt:
        packages:
          - oracle-java8-installer
  include:
    - jdk: oraclejdk7
      addons:
      apt:
        packages:
          - oracle-java7-installer

before_install:
  - export BUILD_COVERAGE="$([ $TRAVIS_JDK_VERSION == 'oraclejdk8' ] && echo 'true')"

install: echo "No need to run mvn install -DskipTests then mvn install.  Running mvn install."

script: mvn install

after_success:
  - test -z "$BUILD_COVERAGE" || mvn clean test jacoco:report coveralls:report

